### ISSUE TITLE
Show Interface Terse - Pull All Interfaces w/o Name

### ISSUE THREAD

**Issue by Von-dy** [Juniper/py-junos-eznc#763] opened 2017-07-27 14:48 UTC
Hey, I am trying to use the EthPortTable YAML or the get-interface-information RPC in general and I was wondering if there is a way to have them return more than a single interface and more importantly get all interface information without a name. Currently if I run the get-interface-information RPC I end up with the last entry in the table whereas if I was on a Junos Device, I would be able to view information from each interface. 
My current workaround is to call RouteTable, and get each interface name off the RouteTable and then send them one at a time through the get-interface-information RPC. For one, this is a little sloppy and I feel like there should be a better way to do it, which makes me feel like there is but I just haven't seen it yet, and secondly I am afraid that if an Interface isn't used in a route then it won't show up on the RouteTable. There are probably other issues with taking this route, but if anyone has advice for work arounds, anything would help.

**Comment by Von-dy** [comment] 2017-07-27 16:38
I found the issue with why the get-interface-information was not working. I was using the {['format':'json']} argument and that was breaking the output. It would only output the last entry of the table, removing the format argument returns all interfaces. This is still probably something that should be fixed.

**Comment by stacywsmith** [comment] 2017-07-27 16:49
Unfortunately, that's a bug with the JSON output which Junos is producing for the `<get-interface-information>` RPC and not a bug with PyEZ. Please open a JTAC case to address that within Junos. You can tell the JTAC engineer that this may be a case of Junos internal PR 1088814.

**Comment by stacywsmith** [comment] 2017-08-03 22:28
Needs to be addressed in Junos.

**Closed by stacywsmith** 2017-08-03 22:28 UTC
