### ISSUE TITLE
safe_copy() always fail in 2.6.8

### ISSUE THREAD

**Issue by shigechika** [Juniper/py-junos-eznc#1270] opened 2023-10-06 10:17 UTC
I began to use 2.6.8. but safe_copy became always fail.
```
ex3400.example.jp: cleaning filesystem ...
ex3400.example.jp: before copy, computing checksum on remote package: /var/tmp/junos-arm-32-21.4R3-S3.4.tgz
Channel closed.
```
I downgraded to  2.6.7. safe_copy works fine.
```
ex3400.example.jp: cleaning filesystem ...
ex3400.example.jp: before copy, computing checksum on remote package: /var/tmp/junos-arm-32-21.4R3-S3.4.tgz
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 34652160 / 346480633 (10%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 69304320 / 346480633 (20%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 103956480 / 346480633 (30%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 138592256 / 346480633 (40%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 173244416 / 346480633 (50%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 207896576 / 346480633 (60%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 242548736 / 346480633 (70%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 277184512 / 346480633 (80%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 311836672 / 346480633 (90%)
ex3400.example.jp: b'junos-arm-32-21.4R3-S3.4.tgz': 346480633 / 346480633 (100%)
ex3400.example.jp: after copy, computing checksum on remote package: /var/tmp/junos-arm-32-21.4R3-S3.4.tgz
ex3400.example.jp: checksum check passed.
```
The point of a program is the follows:
```
            sw = SW(dev)
            result = sw.safe_copy(
                'junos-arm-32-21.4R3-S3.4.tgz',
                remote_path='/var/tmp',
                progress=True,
                cleanfs=True,
                cleanfs_timeout=300,  # default 300
                checksum='4fe83d4abbecdd47a5c2f391e4341105'
                checksum_timeout=900,  # default 300
                checksum_algorithm='md5',
                force_copy=False,
            )
```

**Comment by chidanandpujar** [comment] 2023-10-09 09:37
Hi @shigechika 
    Thanks,
    Above script works for me on PyEZ 2.6.8 , could you please check ,if it is related to safe_copy .

from jnpr.junos import Device
from jnpr.junos.utils.sw import SW

dev = Device(host='xx.xx.xx.xx', user='xyz', password='xyz')
dev.open()
sw = SW(dev)
result = sw.safe_copy(
   'jinstall-ex-4200-12.3-20180426.0-domestic.tgz',
    remote_path='/var/tmp',
    progress=True,
    cleanfs=True,
    cleanfs_timeout=300,  # default 300
    checksum='4eb9a0c005bd3d231af715aaa4d155c9',
    checksum_timeout=900,  # default 300
    checksum_algorithm='md5',
    force_copy=False,
)

```/sw_install_member_new_issues/py-junos-eznc/tests/functional# python test_safe_copy.py 
10.220.2.107: cleaning filesystem ...
10.220.2.107: before copy, computing checksum on remote package: /var/tmp/jinstall-ex-4200-12.3-20180426.0-domestic.tgz
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 11272192 / 112658290 (10%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 22544384 / 112658290 (20%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 33800192 / 112658290 (30%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 45072384 / 112658290 (40%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 56344576 / 112658290 (50%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 67600384 / 112658290 (60%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 78872576 / 112658290 (70%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 90128384 / 112658290 (80%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 101400576 / 112658290 (90%)
10.220.2.107: b'jinstall-ex-4200-12.3-20180426.0-domestic.tgz': 112658290 / 112658290 (100%)
10.220.2.107: after copy, computing checksum on remote package: /var/tmp/jinstall-ex-4200-12.3-20180426.0-domestic.tgz
10.220.2.107: checksum check passed.

```

**Comment by chidanandpujar** [comment] 2023-11-02 11:43
Hi @shigechika 
    Closing this issue as of now , 
    Please feel free to re-open the issue , once it reproduces.

Thanks

**Closed by chidanandpujar** 2023-11-02 11:43 UTC
Labels: Status: Need Info
