### ISSUE TITLE
PyEZ application is throwing exception while establishing the outbound-ssh connection

### ISSUE THREAD

**Issue by AkhilKumarJha** [Juniper/py-junos-eznc#1198] opened 2022-08-02 09:24 UTC
Junos PyEZ application is throwing exception while establishing the outbound-ssh connection. Logs from cMGD instance where outbound-ssh  is configured and server where Junos PyEZ application is running are shared below: 

Configuration for  outbound-ssh  on cMGD
++++++++++++++++++++++++++++++++++++++++++++

[edit]
root@cmgd# show system services outbound-ssh 
traceoptions {
    file obssh;
    flag all;
}
client nsm_cont {
    device-id akhil-cmgd-test;
    secret "$9$5QnCRhrWLxcyMX-dg4QFn/CuIEy"; ## SECRET-DATA
    keep-alive {
        retry 10;
        timeout 12;
    }
    services netconf;
    10.221.151.254 port 11111;
}

[edit]
root@cmgd# 

root@cmgd:/# tail -f /var/log/obssh
Aug  2 08:42:23 sdxd_obssh_retry_timer_handler: (nsm_cont) Checking for pid: 45110
Aug  2 08:42:23 outbound_ssh_connect_to_server: ri_name =  Connection to: 10.221.151.254 port: 11111 failed: Error - Connection refused
Aug  2 08:42:38 sdxd_obssh_retry_timer_handler: (nsm_cont) Checking for pid: 45112
Aug  2 08:42:38 outbound_ssh_connect_to_server: ri_name =  Connection to: 10.221.151.254 port: 11111 failed: Error - Connection refused
Aug  2 08:42:53 sdxd_obssh_retry_timer_handler: (nsm_cont) Checking for pid: 45114
Aug  2 08:42:53 outbound_ssh_connect_to_server: ri_name =  Connection to: 10.221.151.254 port: 11111 failed: Error - Connection refused
Aug  2 08:43:08 sdxd_obssh_retry_timer_handler: (nsm_cont) Checking for pid: 45116
Aug  2 08:43:08 outbound_ssh_connect_to_server: ri_name =  Connection to: 10.221.151.254 port: 11111 failed: Error - Connection refused
Aug  2 08:43:23 sdxd_obssh_retry_timer_handler: (nsm_cont) Checking for pid: 45118
Aug  2 08:43:23 outbound_ssh_connect_to_server: ri_name =  Connection to: 10.221.151.254 port: 11111 failed: Error - Connection refused
Aug  2 08:43:38 sdxd_obssh_retry_timer_handler: (nsm_cont) Checking for pid: 45120
Aug  2 08:43:38 outbound_ssh_connect_to_server: ri_name =  Connection to: 10.221.151.254 port: 11111 failed: Error - Connection refused
Aug  2 08:43:53 sdxd_obssh_retry_timer_handler: (nsm_cont) Checking for pid: 45123
Aug  2 08:43:53 outbound_ssh_connect_to_server: ri_name =  Connection to: 10.221.151.254 port: 11111 failed: Error - Connection refused
Aug  2 08:44:08 sdxd_obssh_retry_timer_handler: (nsm_cont) Checking for pid: 45126
^C
root@cmgd:/# 

Server running Junos PyEZ application for establishing the outbound-ssh connection
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

root@ubuntu18-04-3:~/rootCA# python2 obssh_11111.py 
/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.hazmat.backends import default_backend

Listening on port 11111 for incoming sessions ...

 sockfd before 0

Got a connection from 10.206.219.54:47676!
client <socket._socketobject object at 0x7fcea20fa520>
MSG DEVICE-CONN-INFO V1 akhil-cmgd-test
Logging in ...

 sockfd after 4
Calling dev.open
DEBUG:ncclient.transport.session:[host None session 0x7fce9ce62290] <SSHSession(session, initial daemon)> created: client_capabilities=<dictionary-keyiterator object at 0x7fce9cedb5f0>
DEBUG:ncclient.transport.ssh:starting thread (client mode): 0x9ce62b50L
DEBUG:ncclient.transport.ssh:Local version/idstring: SSH-2.0-paramiko_2.11.0
DEBUG:ncclient.transport.ssh:Banner: 
ERROR:ncclient.transport.ssh:Exception (client): Error reading SSH protocol banner[Errno 104] Connection reset by peer
ERROR:ncclient.transport.ssh:Traceback (most recent call last):
ERROR:ncclient.transport.ssh:  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2094, in run
ERROR:ncclient.transport.ssh:    self._check_banner()
ERROR:ncclient.transport.ssh:  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2276, in _check_banner
ERROR:ncclient.transport.ssh:    "Error reading SSH protocol banner" + str(e)
ERROR:ncclient.transport.ssh:SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
ERROR:ncclient.transport.ssh:
Traceback (most recent call last):
  File "obssh_11111.py", line 74, in <module>
    main()
  File "obssh_11111.py", line 68, in main
    dev.open()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 1379, in open
    raise EzErrors.ConnectRefusedError(self)
jnpr.junos.exception.ConnectRefusedError: ConnectRefusedError(None)
root@ubuntu18-04-3:~/rootCA# 
root@ubuntu18-04-3:~/rootCA#

**Comment by dineshbaburam91** [comment] 2022-08-02 13:53
The issue is on cmgd sshd side, it is not a PyEZ issue. 

Closing the issue,

**Closed by dineshbaburam91** 2022-08-02 13:53 UTC
