### ISSUE TITLE
utils.scp and utils.start_shell is hardcode to port 22

### ISSUE THREAD

**Issue by jnpr-raylam** [Juniper/py-junos-eznc#678] opened 2017-03-09 03:19 UTC
in SCP.open:
```
        self._ssh.connect(hostname=junos._hostname,
                          port=(
                              22, int(
                                  junos._port))[
                              junos._hostname == 'localhost'],
                          username=junos._auth_user,
                          password=junos._auth_password,
                          sock=sock, **kwargs
                          )
```
in StartShell.open:
```
        self._ssh.connect(hostname=junos._hostname,
                          port=(
                              22, int(
                                  junos._port))[
                              junos._hostname == 'localhost'],
                          username=junos._auth_user,
                          password=junos._auth_password,
                          sock=sock, **kwargs
                          )
```
Both are hard-coded to use port 22 if the hostname is not 'localhost'
My use case is the Junos devices are sitting beside a DNAT device and doesn't use the port 22/830 to connect.

Can we modify to use the provided port number for using the scp and start_shell module?
```
port=junos._port
```

Or at least passing in argument to specify using Device._port

**Comment by rahkumar651991** [comment] 2021-06-01 08:36
This is a duplicate of #573 . We will use the older one as it has some discussion. 
Closing this, based on that.

**Closed by rahkumar651991** 2021-06-01 08:36 UTC
