### ISSUE TITLE
jnpr.junos.exception.ConnectError: ConnectError(host: 10.102.165.226, msg: DLL load failed: %1 is not a valid Win32 application.)

### ISSUE THREAD

**Issue by Kalhamdan** [Juniper/py-junos-eznc#577] opened 2016-08-11 10:24 UTC
I've been facing a problem where I cannot connect to a VMM router (virtual routers on server) using the PyEZ dev.open() function for some reason. I have been attempting to troubleshoot this problem for some time now to no avail. Any suggestions would be greatly appreciated.

**Here is my code:**

`import re
import time
from jnpr.junos import *
from prettytable import PrettyTable

login = 'test'
passWord = 'test123'

class switch(object):
    def __init__(self, value):
        self.value = value
        self.fall = False

    def __iter__(self):
        """Return the match method once, then stop"""
        yield self.match
        raise StopIteration

    def match(self, *args):
        """Indicate whether or not to enter a case suite"""
        if self.fall or not args:
            return True
        elif self.value in args: # changed for v1.5, see below
            self.fall = True
            return True
        else:
            return False

def devFacts():
    ipList = []

    print("Retrieving device facts...")
    time.sleep(2)

    with open("C:\Users\kalhamdan\Documents\Python resources\VMM-Address.txt") as f:
        for line in f:
            ipList.append(line)

    f.close()

    deviceIp = ipList[0]

    print ("IP to connect to: " + ipList[0])

    print("Connecting to device...")
    time.sleep(2)

    dev = Device(host=deviceIp, user=login, password=passWord, port=22)
    dev.open()
    print("Connected...")
    print (dev.facts)

    dev.close()`

My devFacts() is being called through a switch statement via user input/menu. 

**Here is the output:** 

(1) Device Facts.
(2) Placeholder.
(3) Placeholder.
(4) Placeholder.

Please enter a number: 1
Retrieving device facts...
IP to connect to: 10.102.165.226
Connecting to device...
No handlers could be found for logger "ncclient.transport.ssh"
Traceback (most recent call last):
  File "C:/Users/kalhamdan/PycharmProjects/???/ Scripts/TestATP.py", line 69, in <module>
    devFacts()
  File "C:/Users/kalhamdan/PycharmProjects/???/ Scripts/TestATP.py", line 50, in devFacts
    dev.open()
  File "C:\Python27\lib\site-packages\jnpr\junos\device.py", line 483, in open
    raise cnx_err
jnpr.junos.exception.ConnectError: ConnectError(host: 10.102.165.226, msg: DLL load failed: %1 is not a valid Win32 application.)

Process finished with exit code 1

**Here are the libraries I have:** 

cffi (1.7.0)
cryptography (1.4)
distribute (0.7.3)
ecdsa (0.13)
enum34 (1.1.6)
idna (2.1)
ipaddress (1.0.16)
Jinja2 (2.8)
junos-eznc (1.3.1)
lxml (3.6.1)
MarkupSafe (0.23)
ncclient (0.5.2)
netaddr (0.7.18)
paramiko (2.0.2)
pip (8.1.2)
prettytable (0.7.2)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pycrypto-on-pypi (2.3)
pywin32 (220)
PyYAML (3.11)
scp (0.10.2)
setuptools (25.1.6)
six (1.10.0)

Again, I appreciate any help and thanks in advance! :)

**Comment by vnitinv** [comment] 2016-09-02 06:39
@Kalhamdan From your windows machine with the same script are you able to connect to other routers?
To me, it looks like the issue is with your windows environment.

**Comment by vnitinv** [comment] 2016-09-07 06:06
@Kalhamdan I am closing this issue as PyEZ is not using any shared library. This issue is coming from any other 3rd party library on your windows device.

**Closed by vnitinv** 2016-09-07 06:06 UTC
