### ISSUE TITLE
device.facts aren't gathered until printed (?) when using Device as a context manager

### ISSUE THREAD

**Issue by DeepSpace2** [Juniper/py-junos-eznc#774] opened 2017-08-17 15:56 UTC
I know the title is odd, but please consider the following code:

```python
with Device(host=ip, user=juniper_devices_username,
            password=juniper_devices_password, port=juniper_devices_port) as device:
    # print(device.facts)
    device.facts_refresh()
    devices_facts_cache[ip] = device.facts
```
Unless I uncomment `print(device.facts)` all the facts at `devices_facts_cache[ip]` will have `None` as value. It is enough to uncomment `print(device.facts)` for the facts to be gathered. I've tried passing `gather_facts=True` to `Device(...)` but the issue still persists. Forcing new style doesn't make a change either.

I'm using version 2.1.5.

**Comment by stacywsmith** [comment] 2017-08-17 18:07
@DeepSpace2 

With the default "new style" fact gathering introduced in PyEZ 2.1.0, this is expected behavior. There's also a fairly simple workaround.

Previously, the `facts` attribute was a standard Python dictionary, and querying of the device to populate the facts occurred at the time that `device.facts_refresh()` was called (either directly or indirectly via `device.open()`.)  Fact gathering introduced a noticeable delay in the `dev.open()` call while the necessary RPCs were executed to gather facts from the device. As more facts were added to the dictionary, this delay increased. There was no option to gather a subset of facts from the device.

PyEZ 2.1.0 introduced "new style" fact gathering which is performed "on demand". The device's facts attribute is no longer a standard Python dictionary. It's actually a custom class which behaves like a standard Python dictionary. You can see this with:
```
>>> type(device.facts)
<class 'jnpr.junos.factcache._FactCache'>
```

Now, when a particular key is accessed in the `device.facts` attribute, the `device.facts` object looks in it's internal cache for the value of that key. If the key exists in its internal cache, it simply returns the value from its cache without sending any RPCs to the device. If the key does not yet exist in the `device.facts` object's internal cache, then it executes the necessary RPCs against the Junos device in order to determine the key's value. It then caches the value, and returns the value to the user.

The advantage of this approach is that querying the value of a specific fact such as `device.facts['hostname']` will only result in sending the minimal RPCs to the device in order to populate the specific `device.facts['hostname']` fact. Subsequent queries for the same value do not send any RPC to the device.

If you attempt to print the entire `device.facts` object, it indirectly accesses every key in the ojbect (the same as a dictionary would). Except, in this case, that key access is what causes the key's value to be populated on demand.

This means that the behavior of `device.fact_refresh()` also changes. Rather than causing an immediate refresh of the facts, it simply causes the internal cache of the `device.facts` object to be emptied. The result is that a particular fact will be refreshed the next time it is accessed, not at the time that `device.facts_refresh()` is called.

With the "old style" fact gathering there was also somewhat undefined behavior if there was a problem gathering a particular fact from a device. In some cases an exception was raised. In some cases, an exception was not raised, but fact gathering stopped and additional facts were not populated. In that situation, accessing one of the facts that wasn't gathered resulted in a `KeyError` exception. If the key did exist, it's value was not well defined.

With "new style" fact gathering, all fact keys are guaranteed to exist. That means you will only get a `KeyError` if you query an unknown fact such as `device.facts['foo']`. If there is an problem retrieving the value of a particular fact, then "new style" fact gathering will consistently return the value `None` for that fact. Exceptions will not be raised during the fact gathering process unless `device.facts_refresh(exception_on_failure=True)` has been called.

Now, lets look at how this applies when using a context manager. When using a PyEZ Device object in a context manager, an implicit `device.open()` occurs when you enter the context, and an implicit `device.close()` occurs when you exit the context.

In your code, `devices_facts_cache[ip] = device.facts` assigns `devices_facts_cache[ip]` to be a reference to the `device.facts` object. If you then exit the context, the `device.facts` object continues to exist because it is referenced by `devices_facts_cache[ip]`. When you attempt to access the values in the object (either directly, or indirectly by printing) the object continues to behave exactly as before. If the value is in its internal cache, it returns the value from its cache. If the value is not in its internal cache, then it attempts to send the necessary RPCs to the device in order to determine the value. Except in this case, the connection to the device has already been closed when you exited the context. This results in an exception. The exception is caught and the value `None` is assigned to the fact. This results in the reported behavior where all facts have the value `None`.

If you execute the `print(device.facts` statement within the context manager, this causes all facts to be populated in the `device.facts` objects internal cache. When you then exit the context manager, `devices_facts_cache[ip]` continues to be a reference to the `device.facts` object. The difference now is that the `device.facts` object has all the values in it's internal cache and will return them even though the connection to the device has already been closed.

The simple workaround is to change this line:
```
devices_facts_cache[ip] = device.facts
```

to be:
```
devices_facts_cache[ip] = dict(device.facts)
```

This causes all of the keys in the `device.facts` object to be accessed (and therefore populated). It then converts the result into a true Python dictionary, and assigns that value to `devices_facts_cache[ip] `. The result is that `devices_facts_cache[ip]` is now a true Python dictionary and all of the key/value pairs in the dictionary are a copy, not a reference, to the key/values in the `device.facts` object.

While you are at it, you can remove the:
```
device.facts_refresh()
```
Calling it before you've access any facts is essentially a no-op. It's emptying the already empty internal cache of the `device.facts` object.

Please let me know if any of this isn't clear.

**Closed by stacywsmith** 2017-08-17 18:07 UTC

**Comment by DeepSpace2** [comment] 2017-08-17 18:19
@stacywsmith 👍
