### ISSUE TITLE
Deprecation warninig - collections import for python 3.3+, stop working on 3.9

### ISSUE THREAD

**Issue by qaxi** [Juniper/py-junos-eznc#1089] opened 2020-11-12 12:16 UTC
On python 3.8 there s deprecation warning
```
/usr/local/lib/python3.8/dist-packages/jnpr/junos/factcache.py:10
  /usr/local/lib/python3.8/dist-packages/jnpr/junos/factcache.py:10: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    class _FactCache(collections.MutableMapping):

```

**Comment by tirkarthi** [comment] 2020-11-17 05:47
This looks like a duplicate of https://github.com/Juniper/py-junos-eznc/issues/1033

**Comment by rahkumar651991** [comment] 2021-06-01 03:57
closing as it is duplicate of #1033

**Closed by rahkumar651991** 2021-06-01 03:57 UTC
Labels: Status: Duplicate
