### ISSUE TITLE
cli_to_rpc_string() generating incorrect rpc string if <app> tag text contains a hyphen char

### ISSUE THREAD

**Issue by ipmonk** [Juniper/py-junos-eznc#1260] opened 2023-08-31 06:46 UTC
// the following generates output that results in an exception

```
>>> d.cli_to_rpc_string("show platform app-controller app l2ald-agent complete")
"rpc.app_controller_show(app='l2ald-agent', complete=True)"

>>> d.rpc.app_controller_show(app='l2ald-agent', complete=True)
/usr/lib64/python3.7/site-packages/jnpr/junos/device.py:858: RuntimeWarning: An unknown exception occurred - please report.
  "An unknown exception occurred - please report.", RuntimeWarning
```

// this is due to the hyphen inside the \<app\> tag. substitute for an underscore and the rpc works:

```
>>> d.rpc.app_controller_show(app='l2ald_agent', complete=True)
<Element app-object-info at 0x7f9c4008c3c0>
```

// problem originates from the | display xml rpc output. 

```
foo@bar> show platform app-controller app l2ald-agent complete | display xml rpc
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/23.3R1-202308210311.0-EVO/junos">
    <rpc>
        <app-controller-show>
                <app>l2ald-agent</app>   <<<<<
                <complete/>
        </app-controller-show>
    </rpc>
```

**Comment by apurvaraghu** [comment] 2024-02-24 01:33
There doesn't seem to be a issue with the way the 'app' tag is used either with '-' or '_'.
Please find the below output. Kindly check if the issue is still seen

py-junos-eznc/tests# cat issue1260.py 
```
from jnpr.junos import Device
from lxml import etree

with Device(host='x.x.x.x', user='xyz', password='xyz') as dev:
    #sw1 = dev.cli_to_rpc_string("show platform app-controller app l2ald-agent complete")
    #print(sw1)
    sw = dev.rpc.app_controller_show(app='l2ald-agent', complete=True)
    print(sw)
```
```

py-junos-eznc/tests# python3 issue1260.py 
<Element app-object-info at 0x7efcdaf58b40>

```

py-junos-eznc/tests# cat issue1260.py 
```
from jnpr.junos import Device
from lxml import etree

with Device(host='x.x.x.x', user='xyz', password='xyz') as dev:
    #sw1 = dev.cli_to_rpc_string("show platform app-controller app l2ald-agent complete")
    #print(sw1)
    sw = dev.rpc.app_controller_show(app='l2ald_agent', complete=True)
    print(sw)
```

```

py-junos-eznc/tests# python3 issue1260.py 
<Element app-object-info at 0x7f2e32278fc0>

```

```
root@EVOvSCAPA1-RE0-re0> show platform app-controller app l2ald-agent complete | display xml rpc 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/24.2-202402131157.0-EVO/junos">
    <rpc>
        <app-controller-show>
                <app>l2ald-agent</app>
                <complete/>
        </app-controller-show>
    </rpc>
    <cli>
        <banner>{master}</banner>
    </cli>
</rpc-reply>
```


```
root@EVOvSCAPA1-RE0-re0> show platform app-controller app l2ald_agent complete | display xml rpc    
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/24.2-202402131157.0-EVO/junos">
    <rpc>
        <app-controller-show>
                <app>l2ald_agent</app>
                <complete/>
        </app-controller-show>
    </rpc>
    <cli>
        <banner>{master}</banner>
    </cli>
</rpc-reply>
```

**Comment by dineshbaburam91** [comment] 2024-05-06 08:46
Info provided, Closing the ticket.
Kindly reopen the ticket, if you need more info on this issue.

**Closed by dineshbaburam91** 2024-05-06 08:46 UTC
Labels: Type: Bug, Status: Need Info
