### ISSUE TITLE
Dynamic Fact refreshing behaviour different on Telnet and SSH Handles

### ISSUE THREAD

**Issue by d200201123** [Juniper/py-junos-eznc#755] opened 2017-07-05 06:12 UTC
The issue is seen when facts are first called after instantiating a device handle and before opening the connection.

Telnet
====
>>> telnet_handle = Device('<DEVICE>', user=<USER>, passwd=<PASSWORD>, mode='telnet')
>>> telnet_handle.facts
{'2RE': None,
---SNIP---
'version_info': None,
'virtual': None}
 
>>> telnet_handle.open()
Device(soa2-a)
 
>>>telnet_handle.facts
{'2RE': None,     >>> Shows everything as None(Facts not refreshed)
'HOME': None,
'RE0': None,
---SNIP---
'version_info': None,
'virtual': None}

SSH
===
>>>dh1 = Device(<DEVICE>,user=<USER>,passwd=<PASSWORD>,port=22)
>>>dh1.facts
{'2RE': None,
'HOME': None,
'RE0': None,
----SNIP-----
'virtual': None}

>>>dh1.open()
Device(soa2-a)

>>>dh1.facts
{'2RE': True,                    >>>>> facts are refreshed
'HOME': '/var/home/regress',
'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'master',
         'model': 'RE-S-1800x2',
         'status': 'OK',
         'up_time': '11 days, 15 hours, 24 minutes, 10 seconds'},
'RE1': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'backup',
---SNIP---
'version_RE1': '15.1R4-S3',
'version_info': junos.version_info(major=(17, 2), type=R, minor=1, build=11),
'virtual': False}

 Please make the behavior constant among all handles.(Preferable facts are refreshed when called first time after opening a connection)

**Comment by stacywsmith** [comment] 2017-07-05 15:32
Can you please update to the latest (2.1.4) version of PyEZ?
I believe this is a duplicate of #719 and has been addressed by #720 in version >= 2.1.3.

If you are still having problems after upgrading to 2.1.4 please reopen this issue.

**Closed by stacywsmith** 2017-07-05 15:32 UTC
