### ISSUE TITLE
Console over SSH not working in 2.2.0 

### ISSUE THREAD

**Issue by dgarros** [Juniper/py-junos-eznc#877] opened 2018-09-06 17:48 UTC
@vnitinv @mzbroch 
The SSH over console feature introduced in 2.2.0 is not working for me
I wanted to do the integration with the juniper_junos ansible module but it looks broken in Pyez 2.2.0

I did a bit of troubleshooting and I was able to make it work when I change the flag `RECVSZ` to 1, current value is 1024 (in file `lib/jnpr/junos/transport/tty_ssh.py`)

@vnitinv, looks like you changed it from 1 to 1024 in #870, any specific raison for that ? 

Happy to send a PR to flip it back to 1 if we agreed it's the right fix

**Comment by mzbroch** [comment] 2018-09-11 07:01
@vnitinv @dgarros 

RECVSZ has been set to minimum value of 1 to chunk data and allow for reading newline characters. Read, readline, read_until are method commonly used for other transports already implemented and I took a design decision to mimic same behaviour for ssh transport. 

According to my tests, setting higher value of RECVSZ will break the feature in *most* cases, this is due to standard behaviour that declared portion of the SSH (Paramiko) buffer data will be read, however it can be more data than matched/expected by the regexp.

As there are already many sleeps (both time.sleep and select) within the code in multiple places, setting value of 1 to RECVSZ as per original commit had no significant impact on the performance during tests performed - my user experience during transfers with latency ~150ms was very good in this case, as the lowest buffer is not being used for the read_until method which generates the most traffic (it transfers netconf data).

**Comment by dgarros** [comment] 2018-09-11 17:39
Thanks @mzbroch for these information, I created a PR to change this value
#881

**Comment by vnitinv** [comment] 2018-09-12 05:33
@dgarros  Reason for changing it to 1024, Over SSH do we really need such slow read.
with setting it to 1, the state machine will be called on every char read. Will impact performance.

On CLI we sometimes see a message like
`Type the hot key to suspend the connection: <CTRL>Z`
with every char read, when it reaches `Type the hot key to suspend the connection: <CTRL>`
(without Z) it match CLI option and hence state machine breaks down to login.
https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/transport/tty.py#L55

We need to see why 1024, is cauing issue on your setup and fix accordingly.

@stacywsmith any comment?

**Comment by dgarros** [comment] 2018-09-13 05:50
@vnitinv, have you been able to test the code successfully with 1024 ? based on @mzbroch comment, it looks like it shouldn't work in most cases.

In my case, when i try to initiate a connection with 1024, the login phase is going well, but once netconf start the library is not able to detect the end of transmission string `]]>]]>`
Happy to have a troubleshooting session with you on our setup or to give you access to one of our console server.

**Comment by stacywsmith** [comment] 2018-09-13 13:48
> @stacywsmith any comment?
Sorry, nothing off the top of my head and I don't currently have cycles to investigate.

**Comment by dgarros** [comment] 2018-09-14 16:56
@vnitinv @ydnath how can we move forward regarding this issue ?

I'm available to troubleshot with you but if we can't find the better solution quickly I would recommend to revert the value to 1
As far as I understand the performance impact is not that visible with 1 but at least it's working for us.

Thanks

**Comment by mzbroch** [comment] 2018-09-15 13:02
@dgarros @vnitinv 
The most important from the performance point of view is receive() function in the tty_netconf.py. That one calls read_prompt, which uses bigger buffer size and works ok with that - in an effect, in case of long outputs / reads from the Device, we can use more than 1 byte in a single read. I was testing this against production configuration files and no issues were identified here - transfers were working well.

One byte read is used only in login to read prompt and only in opening netconf session. Although, this setting might slow down the process, it should not be visible from the user experience point of view.

Please also know, that we receive (read) one byte from the Channel - it does not mean we use such a small TCP Window Size - the data we read is already buffered.

**Comment by dgarros** [comment] 2018-09-18 17:57
@vnitinv @ydnath this issue is a big blocker for us, we would really appreciate your help here to resolve that quickly.

**Comment by vnitinv** [comment] 2018-09-19 11:27
@mzbroch for me more than the speed, the concern was the issue I faced described at https://github.com/Juniper/py-junos-eznc/issues/877#issuecomment-420517597
I need to understand why reading 1024 is breaking your setup.

**Comment by mzbroch** [comment] 2018-09-19 11:37
@vnitinv I think I might have said that before: with 1024 value, you take some portion of the data from the buffer, but you process it only until regexp match. It means, that data "after" the regexp is left behind. Next recv() operation won't use it.

**Comment by vnitinv** [comment] 2018-09-19 12:10
@dgarros @mzbroch Can you share me the output for below script:

```python
from jnpr.junos import Device
import logging
logging.basicConfig(level=logging.DEBUG)

with Device(host="xx.xx.xx.xx", user="xxx", passwd="xxx", cs_user='xxxx', cs_passwd='xxx') as dev:
    print(dev.cli("show version"))
```
@mzbroch My understanding is, while login, we will just get a prompt (end of string) for a user input. 
Then we need to write data. So there shouldnt be a case of partial usage of already readout data.

**Comment by mzbroch** [comment] 2018-09-19 15:05
@vnitinv @dgarros I sent you an output via email thread.

**Comment by vnitinv** [comment] 2019-01-30 06:03
@dgarros @mzbroch Closing this issue for now. Please do re-open if the issue is still seen.

**Closed by vnitinv** 2019-01-30 06:03 UTC

**Comment by AJNOURI** [comment] 2019-11-13 09:18
@vnitinv
Using the script you provided, where can we designate the asynchronous port through which a switch is connected to the terminal server.

Here is an example of a terminal server:

Port    Port Name       Access    Speed  TCP Port  SSH port     Device
  1  	device01        Remote     9600     2100      2122      /dev/ttyGN0 
  2  	device02        Remote     9600     2200      2222      /dev/ttyGN1 
...
 11  device11        Remote     9600     3100      3122     /dev/ttyGN10 
 12  device21        Remote     9600     3200      3222     /dev/ttyGN11 
...
Type a key to continue, q to quit
InReach:0 >



import sys
from getpass import getpass
from jnpr.junos import Device
from jnpr.junos.exception import ConnectError

hostname = input("Console server hostname: ")
cs_username = input("Console server username: ")
cs_password = getpass("Console server or SSH key password: ")
junos_username = input("Junos OS username: ")
junos_password = getpass("Junos OS password: ")

try:
    with Device(host=hostname, user=junos_username, passwd=junos_password, 
            cs_user=cs_username, cs_passwd=cs_password, timeout=6) as dev:   
        print (dev.facts)
except ConnectError as err:
    print ("Cannot connect to device: {0}".format(err))
    sys.exit(1)
except Exception as err:
    print (err)
    sys.exit(1)



Result:

ConnectRefusedError: ConnectRefusedError(terminal_server)

Which I guess, normal because the script doesn't know to what switch to connect.

Any hint?

**Comment by vnitinv** [comment] 2020-04-23 05:34
@AJNOURI Sorry for such a long delay in response. I might need to get a similar setup to debug what needs to be fixed (if any). Will get back to you.

**Comment by ntwrkguru** [comment] 2020-04-23 12:36
Have you tried connecting to the SSH port in the Device constructor? i.e.

```
    with Device(host=hostname, user=junos_username, passwd=junos_password, 
            cs_user=cs_username, cs_passwd=cs_password, port=2122, timeout=6) as dev:
```
