### ISSUE TITLE
safe_copy sometimes timeout

### ISSUE THREAD

**Issue by shigechika** [Juniper/py-junos-eznc#1138] opened 2021-11-19 07:34 UTC
I like safe_copy design that do local/remote checksum and copy and verify remote.
but safe_copy fail sometime timeout cause by RpcTimeoutError.
I try to increase checksum_timeout value 300(default), 600, 900(now), but does not resolve now.

I guess that the COPY is always works well but after the COPY, REMOTE CHECKSUM sometimes timeout...😭

```
dev.facts
 'junos_info': {'fpc0': {'object': junos.version_info(major=(18, 4), type=R, minor=3-S7, build=2),
                         'text': '18.4R3-S7.2'}},
 'master': 'RE0',
 'model': 'EX3400-24T',
 'model_info': {'fpc0': 'EX3400-24T'},

case 1
RpcTimeoutError(host: host1, cmd: get-checksum-information, timeout: 300)

case2
RpcTimeoutError(host: host2, cmd: get-checksum-information, timeout: 600)

case3
RpcTimeoutError(host: host3, cmd: get-checksum-information, timeout: 900)

case 4 source and log

    # copy
    try:
        sw = SW(dev)
        result = sw.safe_copy(
            : snip
            progress=True,
            cleanfs=True,
            cleanfs_timeout=300,  # default 300
            checksum_timeout=900,  # default 300
            force_copy=False,
        )
        : snip
    except RpcTimeoutError as err:
        print("Copy failure caused by RpcTimeoutError:", err)
        return True

host4: cleaning filesystem ...
host4: before copy, computing checksum on remote package: /var/tmp/junos-arm-32-18.4R3-S10.tgz
host4: b'junos-arm-32-18.4R3-S10.tgz': 32129024 / 321129855 (10%)
host4: b'junos-arm-32-18.4R3-S10.tgz': 64241664 / 321129855 (20%)
host4: b'junos-arm-32-18.4R3-S10.tgz': 96354304 / 321129855 (30%)
host4: b'junos-arm-32-18.4R3-S10.tgz': 128466944 / 321129855 (40%)
host4: b'junos-arm-32-18.4R3-S10.tgz': 160579584 / 321129855 (50%)
host4: b'junos-arm-32-18.4R3-S10.tgz': 192692224 / 321129855 (60%)
host4: b'junos-arm-32-18.4R3-S10.tgz': 224804864 / 321129855 (70%)
host4 b'junos-arm-32-18.4R3-S10.tgz': 256917504 / 321129855 (80%)
host4: b'junos-arm-32-18.4R3-S10.tgz': 289030144 / 321129855 (90%)
host4: b'junos-arm-32-18.4R3-S10.tgz': 321129855 / 321129855 (100%)
host4: after copy, computing checksum on remote package: /var/tmp/junos-arm-32-18.4R3-S10.tgz
Copy failure caused by RpcTimeoutError: RpcTimeoutError(host: host4, cmd: get-checksum-information, timeout: 900)
```

Do you have any idea to fix?💡

**Comment by chidanandpujar** [comment] 2021-11-27 10:13
Hi ,
could you please try with checksum algorithms sha1 or sha256 and checksum options .

from jnpr.junos import Device
from jnpr.junos.utils.sw import SW

dev = Device(host='xx.xx.xx.xx', user='xyz', password='xyz', gather_facts=False)
dev.open()

try:
   sw = SW(dev)
   result = sw.safe_copy(
            package="xyz.vmdk",
            remote_path="/var/tmp",
            progress=True,
            cleanfs=True,
            cleanfs_timeout=300,
            checksum_timeout=300,
            force_copy=False,
            checksum ="2e4aa9a91bb5d7ce0c83390e39e230781",
            checksum_algorithm="sha256",
   )
except Exception as err:
    print("Copy failure caused by Error:", err)

Thanks & Regards
Chidanand

**Comment by dineshbaburam91** [comment] 2022-07-05 10:42
@shigechika Kindly validate the @chidanandpujar code snippet solution.  If you face an issue, please feel free to reopen the ticket.
The solution provided. Hence, closing the ticket.

**Closed by dineshbaburam91** 2022-07-05 10:42 UTC
Labels: Type: Question, Status: Need Info, Priority: Low
