### ISSUE TITLE
Config can't replace

### ISSUE THREAD

**Issue by tanzhixu** [Juniper/py-junos-eznc#502] opened 2016-04-21 10:09 UTC
Hi, when i set merge=False and use the below config to replace the old config in SRX, But it's doesn't work, Please Help!!
routing-options {
    replace:
    static {
    route 1.1.19.0/24 next-hop 10.220.88.1;
    route 1.1.16.0/24 next-hop 10.220.88.1;
    }
}

**Comment by vnitinv** [comment] 2016-09-07 05:41
@gaddevijay Can you please help with this. Whether this is an issue with PyEZ or expected behaviour.

**Comment by gaddevijay** [comment] 2016-09-07 05:53
Config seems to be fine. I tried this on my setup and everything seems to be fine. I do not have SRX, so tried it on M series.

Code:
-----------------------------------------
com = '''routing-options {
replace:
static {
route 1.1.19.0/24 next-hop 10.120.88.1;
route 1.1.16.0/24 next-hop 110.120.88.1;
}
}'''
rsp = cfg.load(com, merge=False)
---------------------------------------


Response:
-----------------------------------------
DEBUG:ncclient.transport.session:queueing <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:c26e7228-74be-11e6-aff5-9cf387ab1da2"><load-configuration action="replace" format="text"><configuration-text>routing-options {
replace:
static {
route 1.1.19.0/24 next-hop 10.120.88.1;
route 1.1.16.0/24 next-hop 110.120.88.1;
}
}</configuration-text></load-configuration></nc:rpc>
DEBUG:ncclient.operations.rpc:Sync request, will wait for timeout=30
DEBUG:ncclient.transport.ssh:Sending message
<Element load-configuration-results at 0x10e03bec8>
DEBUG:ncclient.transport.ssh:parsed new message
DEBUG:ncclient.transport.session:dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x10dff6e10>: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/14.1I0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:c26e7228-74be-11e6-aff5-9cf387ab1da2">
<load-configuration-results>
<ok/>
</load-configuration-results>
</rpc-reply>
------------------------------------------


On Router:
-----------------------------------------
regress@irtb4-d# show routing-options 
static {
    route 1.1.19.0/24 next-hop 10.120.88.1;
    route 1.1.16.0/24 next-hop 110.120.88.1;
}

[edit]
regress@irtb4-d# 

---------------------------------------

**Comment by vnitinv** [comment] 2016-09-07 06:04
@tanzhixu Closing this for now as it looks to be working with latest code.

**Closed by vnitinv** 2016-09-07 06:04 UTC
